package org.trustweave.credential.vi

import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldContain
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain as stringShouldContain
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.jupiter.api.Test

/**
 * Known-answer cross-stack interop test for [VerifiableIntent.verifyChain].
 *
 * The fixture `vi_autonomous_fixture.json` was generated by the **reference Python implementation**
 * (`agent-intent/verifiable-intent`) and self-verified valid on both sides before being committed.
 * Passing it here proves the Kotlin port reproduces the spec's security-critical mechanisms —
 * cross-layer `sd_hash` chaining, SD-JWT array-element disclosures, embedded-JWK key resolution, and
 * ES256 — byte-for-byte against an independent stack.
 */
class ChainVerifierKnownAnswerTest {

    private val fixture: JsonObject = run {
        val text = javaClass.getResourceAsStream("/vi_autonomous_fixture.json")!!
            .bufferedReader().use { it.readText() }
        Json.parseToJsonElement(text).jsonObject
    }
    private val tokens = fixture["tokens"]!!.jsonObject
    private val issuerJwk = fixture["issuer_public_jwk"]!!.jsonObject
    private val now = fixture["now"]!!.jsonPrimitive.long

    private fun tok(key: String): String = tokens[key]!!.jsonPrimitive.content

    @Test
    fun `network side - L1 to L2 to L3a payment chain verifies and constraints are satisfied`() {
        val result = VerifiableIntent.verifyChain(
            l1 = tok("l1"),
            l2 = tok("l2_full"),
            issuerJwk = issuerJwk,
            l3Payment = tok("l3a_payment"),
            l2RoutedForPayment = tok("l2_routed_for_network"),
            now = now,
        )

        result.errors.shouldBeEmpty()
        result.valid shouldBe true
        result.checksPerformed shouldContain "l2_reference_binding"
        result.checksPerformed shouldContain "constraints_satisfied"
    }

    @Test
    fun `merchant side - L1 to L2 to L3b checkout chain verifies`() {
        val result = VerifiableIntent.verifyChain(
            l1 = tok("l1"),
            l2 = tok("l2_role_checkout_only"),
            issuerJwk = issuerJwk,
            l3Checkout = tok("l3b_checkout"),
            l2RoutedForCheckout = tok("l2_routed_for_merchant"),
            now = now,
        )

        result.errors.shouldBeEmpty()
        result.valid shouldBe true
        result.checksPerformed shouldContain "open_checkout_contains_line_items"
    }

    @Test
    fun `wrong L2 routing breaks the L3 cross-layer sd_hash binding`() {
        // Feed the merchant's routed presentation where the network's is expected: the L3a sd_hash
        // no longer matches, so the chain MUST fail closed.
        val result = VerifiableIntent.verifyChain(
            l1 = tok("l1"),
            l2 = tok("l2_full"),
            issuerJwk = issuerJwk,
            l3Payment = tok("l3a_payment"),
            l2RoutedForPayment = tok("l2_routed_for_merchant"),
            now = now,
        )

        result.valid shouldBe false
        result.errors.joinToString() stringShouldContain "sd_hash"
    }

    @Test
    fun `expired clock fails closed`() {
        val result = VerifiableIntent.verifyChain(
            l1 = tok("l1"),
            l2 = tok("l2_full"),
            issuerJwk = issuerJwk,
            l3Payment = tok("l3a_payment"),
            l2RoutedForPayment = tok("l2_routed_for_network"),
            now = now + 100_000, // past L1's 24h exp + skew
        )

        result.valid shouldBe false
        result.errors.joinToString() stringShouldContain "expired"
    }
}
