package com.trustweave.credential.chapi.exchange

import com.trustweave.credential.chapi.ChapiService
import com.trustweave.credential.exchange.*
import com.trustweave.credential.exchange.exception.ExchangeException
import com.trustweave.credential.models.VerifiableCredential
import com.trustweave.credential.models.VerifiablePresentation

/**
 * CHAPI (Credential Handler API) implementation of CredentialExchangeProtocol.
 * 
 * Provides credential exchange operations using CHAPI browser API.
 * Supports wallet interactions through browser credential handlers.
 * 
 * **CHAPI Flow:**
 * 1. Issuer creates credential offer (wallet.store())
 * 2. Verifier requests proof (wallet.get())
 * 3. Wallet handles the interaction
 * 
 * **Example Usage:**
 * ```kotlin
 * val chapiService = ChapiService()
 * val protocol = ChapiExchangeProtocol(chapiService)
 * 
 * val registry = CredentialExchangeProtocolRegistry()
 * registry.register(protocol)
 * 
 * val offer = registry.offerCredential("chapi", request)
 * ```
 * 
 * **Browser Integration:**
 * The CHAPI messages generated by this protocol can be used in browser
 * environments with the Credential Handler API:
 * ```javascript
 * navigator.credentials.store(offer.chapiMessage)
 * navigator.credentials.get(proofRequest.chapiMessage)
 * ```
 */
class ChapiExchangeProtocol(
    private val chapiService: ChapiService
) : CredentialExchangeProtocol {
    
    override val protocolName = "chapi"
    
    override val supportedOperations = setOf(
        ExchangeOperation.OFFER_CREDENTIAL,
        ExchangeOperation.ISSUE_CREDENTIAL,
        ExchangeOperation.REQUEST_PROOF,
        ExchangeOperation.PRESENT_PROOF
    )
    
    override suspend fun offerCredential(
        request: CredentialOfferRequest
    ): CredentialOfferResponse {
        // Create CHAPI credential offer
        val offer = chapiService.createCredentialOffer(
            issuerDid = request.issuerDid,
            credentialPreview = request.credentialPreview
        )
        
        return CredentialOfferResponse(
            offerId = offer.offerId,
            offerData = offer.chapiMessage,
            protocolName = protocolName
        )
    }
    
    override suspend fun requestCredential(
        request: CredentialRequestRequest
    ): CredentialRequestResponse {
        throw ExchangeException.OperationNotSupported(
            protocolName = protocolName,
            operation = "REQUEST_CREDENTIAL",
            supportedOperations = supportedOperations.map { it.name }
        )
    }
    
    override suspend fun issueCredential(
        request: CredentialIssueRequest
    ): CredentialIssueResponse {
        // Issue credential via CHAPI
        val issueResult = chapiService.storeCredential(
            credential = request.credential,
            holderDid = request.holderDid
        )
        
        return CredentialIssueResponse(
            issueId = issueResult.credentialId,
            credential = issueResult.credential,
            issueData = issueResult.chapiMessage,
            protocolName = protocolName
        )
    }
    
    override suspend fun requestProof(
        request: ProofRequestRequest
    ): ProofRequestResponse {
        // Create CHAPI proof request
        val proofRequest = chapiService.createProofRequest(
            verifierDid = request.verifierDid,
            requestedAttributes = request.requestedAttributes,
            requestedPredicates = request.requestedPredicates
        )
        
        return ProofRequestResponse(
            requestId = proofRequest.requestId,
            requestData = proofRequest.chapiMessage,
            protocolName = protocolName
        )
    }
    
    override suspend fun presentProof(
        request: ProofPresentationRequest
    ): ProofPresentationResponse {
        // Present proof via CHAPI
        val presentationResult = chapiService.presentProof(
            presentation = request.presentation,
            verifierDid = request.verifierDid
        )
        
        return ProofPresentationResponse(
            presentationId = presentationResult.presentationId,
            presentation = presentationResult.presentation,
            presentationData = presentationResult.chapiMessage,
            protocolName = protocolName
        )
    }
}

