package org.trustweave.did.resolver

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.json.put
import org.trustweave.did.representation.DidMediaTypes
import org.trustweave.did.util.XmlDateTimeSerializer
import org.trustweave.did.util.toXmlDateTime

/**
 * DID resolution metadata per DID Resolution 1.0 §4.2 — metadata about the resolution *process*.
 *
 * Note that `nextUpdate`, `nextVersionId`, `canonicalId` and `equivalentId` are **document**
 * metadata (§4.3) and live on [org.trustweave.did.model.DidDocumentMetadata], not here.
 *
 * **Example:**
 * ```kotlin
 * DidResolutionMetadata(
 *     contentType = DidMediaTypes.DID,
 *     retrieved = Clock.System.now()
 * )
 * ```
 */
@Serializable
data class DidResolutionMetadata(
    /** Media type of the returned `didDocument` (§4.2). OPTIONAL in the spec; always emitted here. */
    val contentType: String = DidMediaTypes.DID,

    /** RFC 9457 error object; MUST be present when resolution is unsuccessful (§4). */
    val error: DidResolutionError? = null,

    /** Proofs generated by the resolver (§4.2). Each entry is a proof map. */
    val proof: List<JsonObject> = emptyList(),

    /** Non-normative: resolution pattern that matched (e.g. `did:web`). */
    val pattern: String? = null,

    /** Non-normative: driver URL when a Universal Resolver driver served the request. */
    val driverUrl: String? = null,

    /** Non-normative: resolution duration in milliseconds (§4.2 lists duration as an example). */
    val duration: Long? = null,

    /** Timestamp the document was retrieved; §3.1 datetime format on the wire. */
    @Serializable(with = XmlDateTimeSerializer::class) val retrieved: Instant? = null,

    /** Additional registered or method-specific members (§4.2 extensibility). */
    val properties: Map<String, String> = emptyMap()
) {
    /** Human-readable error text. */
    @Deprecated("Read error?.detail directly", ReplaceWith("error?.detail"))
    val errorMessage: String? get() = error?.detail

    /** Serializes to the §4.2 JSON structure, omitting absent members. */
    fun toJson(): JsonObject = buildJsonObject {
        put("contentType", contentType)
        error?.let { put("error", it.toJson()) }
        if (proof.isNotEmpty()) put("proof", JsonArray(proof))
        pattern?.let { put("pattern", it) }
        driverUrl?.let { put("driverUrl", it) }
        duration?.let { put("duration", it) }
        retrieved?.let { put("retrieved", it.toXmlDateTime()) }
        properties.forEach { (key, value) -> put(key, JsonPrimitive(value)) }
    }

    /** Flat map view; timestamps use the §3.1 datetime format. */
    fun toMap(): Map<String, Any?> = buildMap {
        put("contentType", contentType)
        error?.let { put("error", it.toJson()) }
        if (proof.isNotEmpty()) put("proof", proof)
        pattern?.let { put("pattern", it) }
        driverUrl?.let { put("driverUrl", it) }
        duration?.let { put("duration", it) }
        retrieved?.let { put("retrieved", it.toXmlDateTime()) }
        if (properties.isNotEmpty()) putAll(properties)
    }

    companion object {
        private val KNOWN_KEYS = setOf(
            "contentType", "error", "errorMessage", "proof",
            "pattern", "driverUrl", "duration", "retrieved", "properties"
        )

        /**
         * Builds metadata from a loosely-typed map, as produced by upstream resolver responses.
         *
         * Accepts both the CR object-valued `error` and the legacy v0.3 string-valued `error`.
         * Unrecognised members are retained in [properties] rather than dropped.
         */
        fun fromMap(map: Map<String, Any?>): DidResolutionMetadata {
            val rawError = map["error"]
            val error = when (rawError) {
                null -> null
                is JsonObject -> DidResolutionError.fromJson(rawError)
                is String -> DidResolutionError.fromJson(JsonPrimitive(rawError))
                is Map<*, *> -> {
                    val type = rawError["type"]?.toString()
                    type?.let {
                        DidResolutionError(
                            type = DidErrorType.fromLegacyCode(it),
                            title = rawError["title"]?.toString()
                                ?: DidErrorType.title(DidErrorType.fromLegacyCode(it)),
                            detail = rawError["detail"]?.toString()
                                ?: map["errorMessage"] as? String
                        )
                    }
                }
                else -> null
            }?.let { parsed ->
                // A legacy response carries its human-readable text in a sibling errorMessage member.
                if (parsed.detail == null) parsed.copy(detail = map["errorMessage"] as? String) else parsed
            }

            return DidResolutionMetadata(
                contentType = (map["contentType"] as? String) ?: DidMediaTypes.DID,
                error = error,
                proof = (map["proof"] as? List<*>)?.filterIsInstance<JsonObject>() ?: emptyList(),
                pattern = map["pattern"] as? String,
                driverUrl = map["driverUrl"] as? String,
                duration = (map["duration"] as? Number)?.toLong(),
                retrieved = (map["retrieved"] as? String)?.let { Instant.parse(it) },
                properties = (map["properties"] as? Map<*, *>)
                    ?.mapNotNull { (k, v) -> (k as? String)?.let { it to (v?.toString() ?: "") } }
                    ?.toMap()
                    ?: map.entries
                        .filter { it.key !in KNOWN_KEYS }
                        .associate { (k, v) -> k to (v?.toString() ?: "") }
            )
        }

        /**
         * Builds metadata from a §4.2 JSON structure.
         *
         * This does not delegate to [fromMap]: a [JsonObject]'s values are [kotlinx.serialization.json.JsonElement]s,
         * so `as? String` casts would silently drop every member.
         */
        fun fromJson(json: JsonObject): DidResolutionMetadata = DidResolutionMetadata(
            contentType = json["contentType"]?.jsonPrimitive?.contentOrNull ?: DidMediaTypes.DID,
            error = DidResolutionError.fromJson(json["error"]),
            proof = (json["proof"] as? JsonArray)?.filterIsInstance<JsonObject>() ?: emptyList(),
            pattern = json["pattern"]?.jsonPrimitive?.contentOrNull,
            driverUrl = json["driverUrl"]?.jsonPrimitive?.contentOrNull,
            duration = json["duration"]?.jsonPrimitive?.longOrNull,
            retrieved = json["retrieved"]?.jsonPrimitive?.contentOrNull?.let { Instant.parse(it) },
            properties = json.entries
                .filter { it.key !in KNOWN_KEYS }
                .mapNotNull { (k, v) -> (v as? JsonPrimitive)?.content?.let { k to it } }
                .toMap()
        )
    }
}
