package org.trustweave.credential.chapi.exchange

import org.trustweave.credential.chapi.ChapiService
import org.trustweave.credential.exchange.*
import org.trustweave.credential.exchange.capability.ExchangeProtocolCapabilities
import org.trustweave.credential.exchange.exception.ExchangeException
import org.trustweave.credential.exchange.model.ExchangeMessageEnvelope
import org.trustweave.credential.exchange.model.ExchangeMessageType
import org.trustweave.credential.exchange.request.ExchangeRequest
import org.trustweave.credential.exchange.request.ProofExchangeRequest
import org.trustweave.credential.identifiers.ExchangeProtocolName
import org.trustweave.credential.model.vc.VerifiableCredential
import org.trustweave.credential.model.vc.VerifiablePresentation
import kotlinx.serialization.json.*

/**
 * CHAPI (Credential Handler API) implementation of CredentialExchangeProtocol.
 *
 * Provides credential exchange operations using CHAPI browser API.
 * Supports wallet interactions through browser credential handlers.
 *
 * **CHAPI Flow:**
 * 1. Issuer creates credential offer (wallet.store())
 * 2. Verifier requests proof (wallet.get())
 * 3. Wallet handles the interaction
 *
 * **Example Usage:**
 * ```kotlin
 * val chapiService = ChapiService()
 * val protocol = ChapiExchangeProtocol(chapiService)
 *
 * val registry = CredentialExchangeProtocolRegistry()
 * registry.register(protocol)
 *
 * val offer = protocol.offer(ExchangeRequest.Offer(...))
 * ```
 *
 * **Browser Integration:**
 * The CHAPI messages generated by this protocol can be used in browser
 * environments with the Credential Handler API:
 * ```javascript
 * navigator.credentials.store(offer.messageData)
 * navigator.credentials.get(proofRequest.messageData)
 * ```
 */
class ChapiExchangeProtocol(
    private val chapiService: ChapiService
) : CredentialExchangeProtocol {

    override val protocolName = ExchangeProtocolName("chapi")

    override val capabilities = ExchangeProtocolCapabilities(
        supportedOperations = setOf(
            ExchangeOperation.OFFER_CREDENTIAL,
            ExchangeOperation.ISSUE_CREDENTIAL,
            ExchangeOperation.REQUEST_PROOF,
            ExchangeOperation.PRESENT_PROOF
        )
    )

    override suspend fun offer(request: ExchangeRequest.Offer): ExchangeMessageEnvelope {
        // Create CHAPI credential offer
        val offer = chapiService.createCredentialOffer(
            issuerDid = request.issuerDid.toString(),
            credentialPreview = request.credentialPreview
        )

        return ExchangeMessageEnvelope(
            protocolName = protocolName,
            messageType = ExchangeMessageType.Offer,
            messageData = offer.chapiMessage
        )
    }

    override suspend fun request(request: ExchangeRequest.Request): ExchangeMessageEnvelope {
        throw ExchangeException.OperationNotSupported(
            protocolName = protocolName.value,
            operation = "REQUEST_CREDENTIAL",
            supportedOperations = capabilities.supportedOperations.map { it.name }
        )
    }

    override suspend fun issue(request: ExchangeRequest.Issue): Pair<VerifiableCredential, ExchangeMessageEnvelope> {
        // Issue credential via CHAPI
        val issueResult = chapiService.storeCredential(
            credential = request.credential,
            holderDid = request.holderDid.toString()
        )

        val envelope = ExchangeMessageEnvelope(
            protocolName = protocolName,
            messageType = ExchangeMessageType.Issue,
            messageData = issueResult.chapiMessage
        )

        return Pair(issueResult.credential, envelope)
    }

    override suspend fun requestProof(request: ProofExchangeRequest.Request): ExchangeMessageEnvelope {
        // Create CHAPI proof request
        val proofRequest = chapiService.createProofRequest(
            verifierDid = request.verifierDid.toString(),
            requestedAttributes = request.proofRequest.requestedAttributes,
            requestedPredicates = request.proofRequest.options.metadata["requestedPredicates"]
                ?.let { it as? JsonObject }
                ?.entries
                ?.associate { it.key to Json.decodeFromJsonElement<org.trustweave.credential.exchange.request.AttributeRequest>(it.value) }
                ?: emptyMap()
        )

        return ExchangeMessageEnvelope(
            protocolName = protocolName,
            messageType = ExchangeMessageType.ProofRequest,
            messageData = proofRequest.chapiMessage
        )
    }

    override suspend fun presentProof(request: ProofExchangeRequest.Presentation): Pair<VerifiablePresentation, ExchangeMessageEnvelope> {
        // Present proof via CHAPI
        val presentationResult = chapiService.presentProof(
            presentation = request.presentation,
            verifierDid = request.verifierDid.toString()
        )

        val envelope = ExchangeMessageEnvelope(
            protocolName = protocolName,
            messageType = ExchangeMessageType.ProofPresentation,
            messageData = presentationResult.chapiMessage
        )

        return Pair(presentationResult.presentation, envelope)
    }
}
