package org.trustweave.credential.didcomm.crypto.rotation

import com.nimbusds.jose.jwk.Curve
import com.nimbusds.jose.jwk.gen.OctetKeyPairGenerator
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.didcommx.didcomm.common.VerificationMaterial
import org.didcommx.didcomm.common.VerificationMaterialFormat
import org.didcommx.didcomm.common.VerificationMethodType
import org.didcommx.didcomm.secret.Secret
import org.slf4j.LoggerFactory
import org.trustweave.credential.didcomm.crypto.secret.LocalKeyStore
import org.trustweave.kms.KeyManagementService
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import kotlin.time.Clock

/**
 * Supplies real creation / usage metadata for a stored DIDComm key.
 *
 * Neither [LocalKeyStore] nor [KeyManagementService] records when a key was created, so rotation
 * decisions need an external source of truth (a metadata table, the key store's own records...).
 */
fun interface KeyMetadataProvider {
    /** Metadata for [keyId], or `null` when it is not known. */
    suspend fun metadataFor(keyId: String): KeyMetadata?
}

/**
 * Manages key rotation for DIDComm keys.
 *
 * Automates key rotation based on policies. A key is only evaluated against the [policy] when its
 * metadata is actually known — from [metadataProvider], or because this manager generated it.
 * Keys with unknown age are never rotated (and are logged), rather than being judged on invented
 * timestamps. Archived keys (`archived-*`) are never rotated.
 *
 * @param metadataProvider Source of real key metadata; without one only keys this manager
 *                         generated itself are eligible for policy-driven rotation.
 */
class KeyRotationManager
    @JvmOverloads
    constructor(
        private val keyStore: LocalKeyStore,
        @Suppress("unused") private val kms: KeyManagementService,
        private val policy: KeyRotationPolicy,
        private val metadataProvider: KeyMetadataProvider? = null,
    ) {
        private val logger = LoggerFactory.getLogger(KeyRotationManager::class.java)

        /** Metadata of keys generated by this manager (their creation time is known exactly). */
        private val generatedKeyMetadata = ConcurrentHashMap<String, KeyMetadata>()

        /**
         * Checks and rotates keys if needed.
         *
         * @return Rotation result
         */
        suspend fun checkAndRotate(): RotationResult =
            withContext(Dispatchers.IO) {
                val keysToRotate = findKeysToRotate()

                val results =
                    keysToRotate.map { keyId ->
                        try {
                            rotateKey(keyId)
                        } catch (cancelled: CancellationException) {
                            throw cancelled
                        } catch (e: Exception) {
                            KeyRotationResult(
                                oldKeyId = keyId,
                                newKeyId = "",
                                success = false,
                                error = e.message,
                            )
                        }
                    }

                RotationResult(
                    rotatedCount = results.count { it.success },
                    results = results,
                )
            }

        /**
         * Rotates a specific key.
         *
         * @param keyId Key ID to rotate
         * @return Rotation result
         */
        suspend fun rotateKey(keyId: String): KeyRotationResult =
            withContext(Dispatchers.IO) {
                // 1. Get current key
                val oldKey =
                    keyStore.get(keyId)
                        ?: throw IllegalArgumentException("Key not found: $keyId")

                // 2. Generate new key
                val newKeyId = generateNewKeyId(keyId)
                val newKey = generateNewKey(newKeyId)

                // 3. Store new key
                keyStore.store(newKeyId, newKey)
                generatedKeyMetadata[newKeyId] = KeyMetadata(keyId = newKeyId, createdAt = Clock.System.now(), lastUsedAt = null)

                // 4. Update DID document (if applicable)
                // This would require DID resolution and update
                // updateDidDocument(keyId, newKeyId)

                // 5. Archive old key (don't delete immediately)
                // Keep for decryption of old messages
                archiveOldKey(keyId, oldKey)

                KeyRotationResult(
                    oldKeyId = keyId,
                    newKeyId = newKeyId,
                    success = true,
                )
            }

        private suspend fun findKeysToRotate(): List<String> {
            val allKeys = keyStore.list().filterNot { it.startsWith(ARCHIVED_PREFIX) }
            return allKeys.filter { keyId ->
                val metadata = getKeyMetadata(keyId)
                if (metadata == null) {
                    logger.warn("Skipping rotation check for DIDComm key '{}': its creation/usage metadata is unknown", keyId)
                    false
                } else {
                    policy.shouldRotate(keyId, metadata)
                }
            }
        }

        private suspend fun getKeyMetadata(keyId: String): KeyMetadata? =
            generatedKeyMetadata[keyId] ?: metadataProvider?.metadataFor(keyId)

        private fun generateNewKeyId(oldKeyId: String): String {
            // Generate new key ID (e.g., increment version or add timestamp)
            val timestamp = System.currentTimeMillis()
            return "$oldKeyId-v$timestamp"
        }

        private suspend fun generateNewKey(keyId: String): Secret {
            val keyPair =
                OctetKeyPairGenerator(Curve.X25519)
                    .keyID(keyId)
                    .generate()
            return Secret(
                keyId,
                VerificationMethodType.JSON_WEB_KEY_2020,
                VerificationMaterial(VerificationMaterialFormat.JWK, keyPair.toJSONString()),
            )
        }

        private suspend fun updateDidDocument(
            oldKeyId: String,
            newKeyId: String,
        ) {
            // Update DID document with new key
            // Implementation depends on DID method
        }

        private suspend fun archiveOldKey(
            keyId: String,
            key: Secret,
        ) {
            // Archive old key (don't delete immediately)
            // Keep for decryption of old messages
            val archivedKeyId = "$ARCHIVED_PREFIX$keyId-${UUID.randomUUID()}"
            keyStore.store(archivedKeyId, key)
        }
    }

private const val ARCHIVED_PREFIX = "archived-"

/**
 * Rotation operation result.
 */
data class RotationResult(
    val rotatedCount: Int,
    val results: List<KeyRotationResult>,
)

/**
 * Individual key rotation result.
 */
data class KeyRotationResult(
    val oldKeyId: String,
    val newKeyId: String,
    val success: Boolean,
    val error: String? = null,
)
