"""Fail CI when the release can be built but not published.

Three failures here are invisible until a release is already in flight: a build with no declared
publishing repository never creates a ``PublishToMavenRepository`` task at all, a POM without
``scm`` is rejected by Maven Central at the staging step rather than at build time, and a POM that
points consumers at a documentation path which no longer exists ships a dead link in every module.

Static checks run anywhere. Generated POMs under the build root, when present, are validated too.
"""
import argparse
import importlib.util
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

_spec = importlib.util.spec_from_file_location("build_root", Path(__file__).with_name("build_root.py"))
_build_root = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_build_root)

POM_NS = {"m": "http://maven.apache.org/POM/4.0.0"}
# Every element Maven Central validation requires beyond the coordinates themselves.
REQUIRED_POM = ("name", "description", "url", "licenses", "developers", "scm")
REQUIRED_SCRIPT = {
    "a publishing repository": re.compile(r"repositories\s*\{[^}]*maven\s*\{", re.S),
    "an scm block": re.compile(r"\bscm\s*\{"),
    "a licenses block": re.compile(r"\blicenses\s*\{"),
    "a developers block": re.compile(r"\bdevelopers\s*\{"),
}
DOC_REFERENCE = re.compile(r"docs/[\w./-]+\.md")
INCLUDE = re.compile(r'include\("([^"]+)"\)')


def check_script(root):
    """Check the root build script declares everything a remote publication needs."""
    script = root / "build.gradle.kts"
    text = script.read_text(encoding="utf-8-sig")
    failures = [f"build.gradle.kts declares no {what}" for what, pattern in REQUIRED_SCRIPT.items() if not pattern.search(text)]
    for reference in sorted(set(DOC_REFERENCE.findall(text))):
        if not (root / reference).is_file():
            failures.append(f"build.gradle.kts points published POMs at {reference}, which does not exist")
    return failures


def module_paths(root):
    """Module output directories, relative to the build root, from settings.gradle.kts."""
    text = (Path(root) / "settings.gradle.kts").read_text(encoding="utf-8-sig")
    return {include.replace(":", "/") for include in INCLUDE.findall(text)}


def check_poms(build_root, modules=None):
    """Validate the POMs Gradle generated for modules this repository still declares.

    A build root is long-lived and is not cleaned between branches, so it accumulates output for
    modules that have since been deleted. Validating those reports failures nobody can fix; they
    are counted as orphans instead, which also makes a stale build root visible.
    """
    failures = []
    build_root = Path(build_root)
    poms = sorted(build_root.glob("**/publications/*/pom-default.xml"))
    orphans = 0
    if modules is not None:
        live = []
        for pom in poms:
            module = pom.parent.parent.parent.relative_to(build_root).as_posix()
            if module in modules:
                live.append(pom)
            else:
                orphans += 1
        poms = live
    for pom in poms:
        text = pom.read_text(encoding="utf-8-sig")
        # These POMs are generated by this build, but ElementTree resolves entities, so refuse a
        # document declaring a DOCTYPE rather than parse one. The other scripts here are stdlib
        # only, so this stays a check instead of a defusedxml dependency CI would have to install.
        if "<!DOCTYPE" in text or "<!ENTITY" in text:
            failures.append(f"{pom.name}: declares a DOCTYPE or entity; a generated POM never does")
            continue
        try:
            root = ET.fromstring(text)
        except ET.ParseError as error:
            failures.append(f"{pom.name}: unparseable ({error})")
            continue
        missing = [element for element in REQUIRED_POM if root.find(f"m:{element}", POM_NS) is None]
        if missing:
            artifact = root.findtext("m:artifactId", default=pom.parent.name, namespaces=POM_NS)
            failures.append(f"{artifact}: POM is missing {', '.join(missing)}")
    return failures, len(poms), orphans


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--build-root", type=Path, default=None)
    args = parser.parse_args()
    try:
        repository = args.root or _build_root.repository_root()
        failures = check_script(repository)
        build = args.build_root or _build_root.resolve(repository)
        if Path(build).is_dir():
            pom_failures, pom_count, orphans = check_poms(build, module_paths(repository))
        else:
            pom_failures, pom_count, orphans = [], 0, 0
        failures.extend(pom_failures)
    except (OSError, ValueError) as error:
        print(f"Invalid publication evidence: {error}", file=sys.stderr)
        sys.exit(1)
    for failure in failures:
        print(failure, file=sys.stderr)
    if failures:
        sys.exit(1)
    stale = f", ignored {orphans} POMs for modules this repository no longer declares" if orphans else ""
    print(f"Publication configuration complete; validated {pom_count} generated POMs{stale}")
