source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-mermaid", "~> 1.0"
gem "jekyll-relative-links", "~> 0.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance and livereload for local development
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

